# Generated by Django 5.2.8 on 2025-11-25 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push')], max_length=20)),
                ('user_id', models.UUIDField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=100)),
                ('variables', models.JSONField()),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('priority', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
