# Generated by Django 5.2.8 on 2025-12-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='push_token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
