# Generated by Django 5.2.8 on 2025-12-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=100, unique=True)),
                ('request_id', models.CharField(max_length=150, unique=True)),
                ('user_id', models.UUIDField()),
                ('push_token', models.CharField(max_length=300)),
                ('template_code', models.CharField(max_length=150)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('delivered', 'delivered'), ('failed', 'failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('processed_title', models.CharField(blank=True, max_length=255)),
                ('processed_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('fcm_response', models.JSONField(blank=True, default=dict)),
                ('fcm_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='push_app.pushnotification')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
